feat: login with keychain, persist with store plugin
Resolvr-io/escrow pull request #39
Opened 2023-12-06 07:42 UTC by ChristianChiarulli

2023-12-06 07:51 UTC, ChristianChiarulli commented
This should allow you to login with your nsec and save it along with your npub using your OS's keychain. It will also store a reference to the public key in a store that is both accessible in the webview as well as on the backend using the tauri store plugin: https://github.com/tauri-apps/tauri-plugin-store

2023-12-06 17:25 UTC, tvolk131 commented on src/pages/LoginPage.tsx
> +// import RegisterForm from "~/components/login/RegisterForm";
Nit: Please remove this.

2023-12-06 17:26 UTC, tvolk131 commented on src/pages/LoginPage.tsx
> +      {/* {formState === "register" && <RegisterForm setFormState={setFormState} />} */}
Nit: Please remove this.

2023-12-06 18:41 UTC, brianjcarroll approved these changes
Im pretty much useless with any Rust review, but as far as the UI goes, all looks good to me.

2023-12-06 18:41 UTC, brianjcarroll commented on src/components/login/LoginForm.tsx
> +  function switchToRegister() {
Curious what this function is doing (and the same fn in RegisterForm) if there are two separate components?

2023-12-06 18:41 UTC, brianjcarroll commented on src/components/login/RegisterForm.tsx
> +  function switchToLogin() {
Same comment as in LoginForm

2023-12-06 21:40 UTC, ChristianChiarulli commented on src/lib/auth.ts
> +}
The keychain should only be accessible by the user. It's actually a feature in this case to have the nsec remain in the keychain for the user to more easily sign in in the future by just selecting their pubkey. I just don't have that implemented yet. Once it is implemented we will then likely want to abstract the login and saving of the nsec to a separate application entirely. Anyway for now I think this is fine.

2023-12-07 00:27 UTC, tvolk131 requested changes

2023-12-07 00:27 UTC, tvolk131 commented on src/components/login/RegisterForm.tsx
> +type Props = {
Nit: `RegisterFormProps`

2023-12-07 00:27 UTC, tvolk131 commented on src/components/profile/UserAvatar.tsx
> +type Props = {
Nit: `UserAvatarProps`

2023-12-07 00:27 UTC, tvolk131 commented on src/components/profile/UserAvatar.tsx
> +  const BOT_AVATAR_ENDPOINT = `https://api.dicebear.com/7.x/bottts-neutral/svg?seed=${seed}`;
Can we move this const out of the component so it's not redefined for each instantiation?

`const BOT_AVATAR_ENDPOINT = "https://api.dicebear.com/7.x/bottts-neutral/svg";`

And then use it within the component like this:

``src={pc(profileMap[pubkey]).picture || `${BOT_AVATAR_ENDPOINT}?seed=${seed}`}``

2023-12-07 00:27 UTC, tvolk131 commented on src/components/ui/use-toast.ts
> +// Inspired by react-hot-toast library
Not a request for changes, just curious why we aren't using `react-hot-toast` directly.

2023-12-07 00:27 UTC, tvolk131 commented on src/lib/auth.ts
> +}
Ah gotcha! So if someone has provided their nSec already, logged out, and is now logging back in with only their pubkey, it would ask for TouchID on MacOS or a password on Windows?

2023-12-07 00:27 UTC, tvolk131 commented on src/lib/auth.ts
> +  const profileEvent = await pool.get(relays, filter);
Please use `RELAYS` from `src/lib/constants.ts`.

2023-12-07 00:32 UTC, ChristianChiarulli commented on src/lib/auth.ts
> +}
yup

2023-12-07 05:16 UTC, ChristianChiarulli commented on src/components/login/LoginForm.tsx
> +            {/* </CardDescription> */}
I'd rather just leave this here for now, since we're moving pretty fast and I plan to come back and implement this functionality soon, but it's your call.

2023-12-07 05:18 UTC, ChristianChiarulli commented on src/stores/eventStore.ts
> +const useEventStore = create<EventState>()(
I think we know what we're talking about here unless you foresee a more generic event store being necessary I'd rather save the verbosity.

2023-12-07 05:20 UTC, ChristianChiarulli commented on src/components/profile/UserAvatar.tsx
> +  }
I'll probably try to come up with a better abstraction at some point, a hook would probably be best, but for now it functionally works.

2023-12-07 06:35 UTC, tvolk131 requested changes
Looks great! Just a few more small things

2023-12-07 06:35 UTC, tvolk131 commented on src-tauri/src/main.rs
> +    Ok(())
Nit: Can we simplify this to: `entry.set_password(nsec).map_err(|e| e.to_string())`? (i.e. remove the `Ok(())` and semicolon)

2023-12-07 06:35 UTC, tvolk131 commented on src/components/header/UserMenu.tsx
> +  }, [profileMap[pubkey]]);
Bump!

2023-12-07 06:35 UTC, tvolk131 commented on src/pages/LoginPage.tsx
> +// import RegisterForm from "~/components/login/RegisterForm";
Bump!

2023-12-07 06:35 UTC, tvolk131 commented on src/lib/nostr.ts
> +      website: "",
Bump!

2023-12-07 06:35 UTC, tvolk131 commented on src/components/profile/UserAvatar.tsx
> +  }
Can you add a TODO comment here (or maybe somewhere else?) mentioning the issue above?

2023-12-07 06:36 UTC, tvolk131 commented on src/components/ui/use-toast.ts
> +// Inspired by react-hot-toast library
Gotcha!

2023-12-07 07:03 UTC, tvolk131 approved these changes
Looking great! Thanks for addressing everything!

2023-12-07 07:07 UTC, merged